### PR TITLE
A More Perfect License

### PR DESCRIPTION
**Pull request by ndo360**
Below I have affixed a revised license. You will need to fill in the placeholder text after accepting the pull request.

### CODE REVIEW

**Comment by mzegar** [comment]
Need to figure out an org name, then we can edit this up and merge it.

**Comment by ndo360** [comment]
May I suggest "Smoking Gun LLC"? :-)

**Comment by objectionist** [comment]
> Need to figure out an org name, then we can edit this up and merge it.

I thought you guys were under the name "Three Thieves" already

**Comment by mzegar** [comment]
@objectionist As talked about in the discord `Three Thieves` is a mapping group/community. Kole and I were in the process of figuring out an org name to license our project under.

**Comment by ndo360** [comment]
Added CLA

**Pull request merged**
