### PR TITLE
Fix: Using doors still feels bad

### PR DESCRIPTION
**Pull request by the-remeko**
Currently, if you are within the usable range of an entity, but are looking at a point on the entity that is outside the usable range, you will not be able to use the entity. This is particularly bad when trying to use a door while looking at it from a shallow angle.

Under these circumstances, Source 1 games run an additional check that essentially finds the closest point on the entity's collision box and allows you to use the entity if that point is within the usable range. That is what I've implemented.

Source 1 games also do other calculations that let you use entities that you are looking close to rather than directly at. When mappers start adding small buttons to their maps, we would probably want to look into this, but I think what I've got here is good enough for doors right now.

### CODE REVIEW

**Comment by mzegar** [comment]
Is this really needed? Do you mind showing me a vid of an odd angle where it wouldn't work before?

**Comment by the-remeko** [comment]
> Is this really needed? Do you mind showing me a vid of an odd angle where it wouldn't work before?

Just stand at one end of the door and try to use it while looking at the far end of the door.

Not having this feature makes doors feel less consistent. Also, this same feature is in gmod and most (all?) Source games.

**Comment by the-remeko** [comment]
> Is this really needed? Do you mind showing me a vid of an odd angle where it wouldn't work before?

Before my change:
https://user-images.githubusercontent.com/94231804/187109979-7ccb21bd-9207-480b-a2cd-a130146ae90f.mp4

After my change:
https://user-images.githubusercontent.com/94231804/187110014-6d98e544-f75f-43a3-9b57-d1fac2caaca4.mp4

**Comment by matekdev** [comment]
@the-remeko still want this? are my changes fine with you?

**Comment by the-remeko** [comment]
Looks good to me.

**Pull request merged**
